name: Locust Performance Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Locust dependencies
        run: pip install -r requirements.txt

      - name: Run Flask API
        run: |
         nohup python run_api.py & 
         sleep 5

      - name: Run Locust performance tests
        run: |
          locust -f locustfile.py --headless --users 20 --spawn-rate 5 --run-time 2m --host=http://localhost:8000 --html report.html --csv results

      - name: Upload Locust test reports
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: |
            report.html
            results*.csv
